### ISSUE TITLE
base64 input 

### ISSUE THREAD

**Issue by nikolaisalnikov** [bumble-tech/private-detector#11]
Hello, I was wondering if there is a possibility to implement a functionality to serve this model straight away using any kind of containerized environment. Specifically, would be nice if the model would be able to accept some kind of standard (e.g base64) image representation instead of tensor representation, since that wouldn't require clients to implement the convertation on their end. Thank you!

**Comment by Steeeephen** [comment]
Hey @nikolaisalnikov,

I really like this idea actually, will talk to the MLE team about bringing it in - should be a quick job

cc @punkerpunker, do you have space to pick this up?

**Comment by punkerpunker** [comment]
Resolved with https://github.com/bumble-tech/private-detector/pull/12
